---
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      # - id: no-commit-to-branch
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.3.0
    hooks:
      - id: check-github-workflows
        name: Check github workflows format
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        args: [--rules, "~MD013"]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.1
    hooks:
      - id: htmllint
        name: HTML linter
  # - repo: https://github.com/pre-commit/mirrors-csslint
  #   rev: v1.0.5
  #   hooks:
  #     - id: csslint
  #       name: CSS linter
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: v7.25.0
  #   hooks:
  #     - id: eslint
  #       name: ECMAScript linter
